<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Estadística Descriptiva - Inferencia estadística univariada</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="..//files/logo-removebg-preview.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Estadística Descriptiva - Inferencia estadística univariada">
<meta property="og:description" content="Recordemos que, en estadística, llamamos inferencia al ejercicio de extrapolar determinadas estimaciones (estadístico) de una muestra a una población más grande (parámetro).">
<meta property="og:image" content="https://descriptiva-facso.netlify.app/files/logo.png">
<meta property="og:site-name" content="Estadística Descriptiva">
<meta property="og:locale" content="en_US">
<meta property="og:image:height" content="500">
<meta property="og:image:width" content="500">
<meta name="twitter:title" content="Estadística Descriptiva - Inferencia estadística univariada">
<meta name="twitter:description" content="Recordemos que, en estadística, llamamos inferencia al ejercicio de extrapolar determinadas estimaciones (estadístico) de una muestra a una población más grande (parámetro).">
<meta name="twitter:image" content="https://descriptiva-facso.netlify.app/files/logo.png">
<meta name="twitter:creator" content="@andreaslaffert">
<meta name="twitter:site" content="@andreaslaffert">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="500">
<meta name="twitter:image-width" content="500">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Estadística Descriptiva</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html">
 <span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html">
 <span class="menu-text">Planificación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../class/index.html">
 <span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../content/index.html" aria-current="page">
 <span class="menu-text">Prácticos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../trabajos.html">
 <span class="menu-text">Trabajos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resource/index.html">
 <span class="menu-text">Recursos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://login.rstudio.cloud/login?redirect=%2F">
 <span class="menu-text">RStudio Cloud</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Inferencia estadística univariada</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Información general</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/index.html" class="sidebar-item-text sidebar-link">Laboratorio de Análisis de Datos</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Sesiones</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/01-content.html" class="sidebar-item-text sidebar-link">1: Introducción al lenguaje R</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/02-content.html" class="sidebar-item-text sidebar-link">2: Conocimientos básicos de programación en R</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/03-content.html" class="sidebar-item-text sidebar-link">3: Procesamiento, limpieza y manipulación de datos en R</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/04-content.html" class="sidebar-item-text sidebar-link">4: Análisis descriptivo de datos en R</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/05-content.html" class="sidebar-item-text sidebar-link">5: Procesamiento y análisis de datos en R</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/06-content.html" class="sidebar-item-text sidebar-link">6: Visualización de datos con R</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/07-content.html" class="sidebar-item-text sidebar-link">7: Forma de una distribución</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/08-content.html" class="sidebar-item-text sidebar-link active">8: Inferencia estadística univariada</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#presentación" id="toc-presentación" class="nav-link active" data-scroll-target="#presentación">Presentación</a>
  <ul class="collapse">
  <li><a href="#objetivo-de-la-práctica" id="toc-objetivo-de-la-práctica" class="nav-link" data-scroll-target="#objetivo-de-la-práctica">Objetivo de la práctica</a></li>
  <li><a href="#recursos-de-la-práctica" id="toc-recursos-de-la-práctica" class="nav-link" data-scroll-target="#recursos-de-la-práctica">Recursos de la práctica</a></li>
  </ul></li>
  <li><a href="#qué-es-la-inferencia-estadística" id="toc-qué-es-la-inferencia-estadística" class="nav-link" data-scroll-target="#qué-es-la-inferencia-estadística">¿Qué es la inferencia estadística?</a></li>
  <li><a href="#preparación-de-datos" id="toc-preparación-de-datos" class="nav-link" data-scroll-target="#preparación-de-datos">Preparación de datos</a>
  <ul class="collapse">
  <li><a href="#cargar-librerías" id="toc-cargar-librerías" class="nav-link" data-scroll-target="#cargar-librerías">1. Cargar librerías</a></li>
  <li><a href="#importar-datos" id="toc-importar-datos" class="nav-link" data-scroll-target="#importar-datos">2. Importar datos</a></li>
  <li><a href="#recodificar" id="toc-recodificar" class="nav-link" data-scroll-target="#recodificar">3. Recodificar</a></li>
  </ul></li>
  <li><a href="#declarar-diseño-muestral" id="toc-declarar-diseño-muestral" class="nav-link" data-scroll-target="#declarar-diseño-muestral">Declarar diseño muestral</a></li>
  <li><a href="#estimaciones-de-punto-y-de-intervalo" id="toc-estimaciones-de-punto-y-de-intervalo" class="nav-link" data-scroll-target="#estimaciones-de-punto-y-de-intervalo">Estimaciones de punto y de intervalo</a>
  <ul class="collapse">
  <li><a href="#a-ic-para-medias-con-diseño-muestral" id="toc-a-ic-para-medias-con-diseño-muestral" class="nav-link" data-scroll-target="#a-ic-para-medias-con-diseño-muestral">a) IC para medias con diseño muestral</a></li>
  <li><a href="#b-ic-para-proporciones-con-diseño-muestral" id="toc-b-ic-para-proporciones-con-diseño-muestral" class="nav-link" data-scroll-target="#b-ic-para-proporciones-con-diseño-muestral">b) IC para proporciones con diseño muestral</a></li>
  <li><a href="#c-varios-a-la-vez" id="toc-c-varios-a-la-vez" class="nav-link" data-scroll-target="#c-varios-a-la-vez">c) Varios a la vez</a></li>
  </ul></li>
  <li><a href="#contraste-de-hipótesis" id="toc-contraste-de-hipótesis" class="nav-link" data-scroll-target="#contraste-de-hipótesis">Contraste de hipótesis</a>
  <ul class="collapse">
  <li><a href="#resumen" id="toc-resumen" class="nav-link" data-scroll-target="#resumen">Resumen</a></li>
  <li><a href="#video-de-la-sesión" id="toc-video-de-la-sesión" class="nav-link" data-scroll-target="#video-de-la-sesión">Video de la sesión</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header">
<h1 class="title d-none d-lg-block display-7">Inferencia estadística univariada</h1>

<div class="date-block bg-content text-white p-2">
  <p class="date">Sesión del jueves, 29 de junio de 2023</p>
</div>
</header>

<section id="presentación" class="level1">
<h1>Presentación</h1>
<section id="objetivo-de-la-práctica" class="level2">
<h2 class="anchored" data-anchor-id="objetivo-de-la-práctica">Objetivo de la práctica</h2>
<p>El objetivo de esta guía práctica es aplicar los conocimientos aprendidos en clases sobre inferencia estadística univariada, comprendiendo sus fundamentos, relevancia y aplicación a un caso concreto en R.</p>
<p>En detalle, aprenderemos:</p>
<ol type="1">
<li><p>Establecer el diseño muestral de una base de datos en R.</p></li>
<li><p>Realizar estimaciones puntuales e intervalares para medias y proporciones.</p></li>
<li><p>Contrastar hipótesis univariadas.</p></li>
</ol>
</section>
<section id="recursos-de-la-práctica" class="level2">
<h2 class="anchored" data-anchor-id="recursos-de-la-práctica">Recursos de la práctica</h2>
<p>En esta práctica trabajaremos con la base de datos de la Encuesta Suplementaria de Ingresos (ESI) del 2021 realizada por el <a href="https://www.ine.gob.cl/">Instituto Nacional de Estadísticas (INE)</a>. Esta base la pueden encontrar en el canal de U-Cursos sección Material Docente, o bien, en el siguiente enlace <a href="https://github.com/Andreas-Lafferte/descriptiva/raw/main/content/Input/data/esi-2021-ocupados.RData"><i class="fa-solid fa-table" aria-hidden="true"></i> <code>ESI 2021</code></a> podrán descargar el archivo que contiene la base ESI 2021.</p>
</section>
</section>
<section id="qué-es-la-inferencia-estadística" class="level1">
<h1>¿Qué es la inferencia estadística?</h1>
<p>Recordemos que, en estadística, llamamos inferencia al ejercicio de <strong>extrapolar</strong> determinadas estimaciones (estadístico) de una muestra a una población más grande (parámetro). En concreto, es el proceso de realizar conclusiones o predicciones sobre una población a partir de una muestra o subconjunto de esa población.</p>
<p><img src="../images/INFERENCIA.jpg" class="img-fluid"></p>
<p>Un concepto central en todo esto es la probabilidad de <em>error</em>, es decir, en qué medida nos estamos equivocando (o estamos dispuestos a estar equivocados) en tratar de extrapolar una estimación muestral a la población.</p>
</section>
<section id="preparación-de-datos" class="level1">
<h1>Preparación de datos</h1>
<section id="cargar-librerías" class="level2">
<h2 class="anchored" data-anchor-id="cargar-librerías">1. Cargar librerías</h2>
<p>Para esta sesión, usaremos librerías que ya conocemos en prácticos pasados y una nueva, llamada <code>srvyr</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, <span class="co"># colección de paquetes para manipulación de datos</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               car, <span class="co"># para recodificar</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               psych, <span class="co"># para analizar datos</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               sjmisc,  <span class="co"># para analizar datos</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               srvyr) <span class="co"># para estimación de IC y ponderadores</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co"># para desactivar notacion cientifica</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># para limpiar el entorno de trabajo</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importar-datos" class="level2">
<h2 class="anchored" data-anchor-id="importar-datos">2. Importar datos</h2>
<p>Cargamos la base de datos ESI 2021 con <code>readRDS</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>esi <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"Input/data/esi-2021-ocupados.RData"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="recodificar" class="level2">
<h2 class="anchored" data-anchor-id="recodificar">3. Recodificar</h2>
<p>Solo recodificamos y convertiremos a factor la variable sexo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>esi<span class="sc">$</span>sexo <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(esi<span class="sc">$</span>sexo, <span class="at">recodes =</span> <span class="fu">c</span>(<span class="st">" 1 = 'Hombre'; 2 = 'Mujer'"</span>), <span class="at">as.factor =</span> T)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="declarar-diseño-muestral" class="level1">
<h1>Declarar diseño muestral</h1>
<p>Como sabemos, <em>las encuestas se basan en procedimientos de muestreos</em>, los cuales debemos declarar para poder realizar el ejercicio de inferencia, o dicho de otra manera, debemos indicar el procedimiento mediante el cual podremos extrapolar nuestras estimaciones a la población.</p>
<p><strong>Por tanto, antes de poder realizar inferencia, debemos tener muy claro el tipo de diseño muestral de nuestra base de datos.</strong></p>
<p>Con <code>srvyr</code>, como primer paso debemos identificar dos variables para poder establecer el diseño muestral en una base de datos:</p>
<ul>
<li>la variable de diseño muestral que incorpora efectos de diseño complejo y,</li>
<li>el ponderador o factor de expansión.</li>
</ul>
<p>Todo este diseño se contiene en variables de la base de datos. Veamos todas las variables que son parte del diseño muestral de la ESI 2021:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   idrph id_identificacion   conglomerado estrato fact_cal_esi
1  14565            102542      820510025 8200111    253.12888
2  24946             69274 13123000144956   13291    238.89778
3  89327             63472      610110021 6100112    161.60639
4 116589             52414  5301000042099    5031     46.40046
5 122766             73953   100691030131   10069     21.67297
6 210896             88382      210110141 2100011    181.86029</code></pre>
</div>
</div>
<p>En el caso de la ESI 2021, la variable que indica el efecto del diseño muestral se llama <em>estrato</em> y la que indica el factor de expansión o ponderador es <em>fact_cal_esi</em>.</p>
<p>Ahora, el segundo paso es crear un objeto <code>survey</code> con estas variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>esi_pond <span class="ot">&lt;-</span> esi <span class="sc">%&gt;%</span> <span class="fu">as_survey_design</span>(<span class="at">ids =</span> <span class="dv">1</span>, <span class="co"># indica conglomerados de muestreo; ~0 o ~1 cuando no hay</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">strata =</span> estrato, <span class="co"># indica efecto de diseño muestral</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">weights =</span> fact_cal_esi) <span class="co"># indica el ponderador</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">survey.lonely.psu =</span> <span class="st">"certainty"</span>) <span class="co"># seteamos para que ids no moleste</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora tenemos una base ponderada además de la original. Esta base ponderada reconoce el diseño muestral y nos permitirá realizar estimaciones que se acerquen al paramétro poblacional.</p>
</section>
<section id="estimaciones-de-punto-y-de-intervalo" class="level1">
<h1>Estimaciones de punto y de intervalo</h1>
<p>Todo estimador está compuesto por dos elementos:</p>
<ul>
<li>Estimación puntual</li>
<li>Precisión (por ejemplo, Intervalos de Confianza “IC”)</li>
</ul>
<p>Perfectamente podemos conocer el valor que obtiene un estadístico a nivel de la población mediante la estimación puntual, pero esto nada nos dice del <em>nivel de certeza o precisión</em> de dicho cálculo. Aquí es donde entran los Intervalos de Confianza (IC).</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="../images/ci.jpeg" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<div class="alert alert-info">
<p>Los IC nos indican un rango de valores que pueden contener el valor poblacional o parámetro desconocido, con un determinado nivel de confianza. Piensa en un IC como una red: es un rango de valores posibles para los parámetros de la población, y podemos tener un X% de confianza (normalmente el 95%) en que la red recoge el parámetro de la población.</p>
<p>Dado que normalmente conocemos valores solo de nuestra muestra, nuestra estimación tendrá cierto grado de incertudumbre. Un IC aborda esta incertidumbre proporcionando un rango de valores dentro del cual creemos que es probable que se encuentre el verdadero parámetro de la población.</p>
<p>Importante: cuando se habla de intervalos de confianza, en realidad no se puede decir nada sobre la estimación del parámetro propiamente tal, sino que nos referimos a la red o al rango en sí.</p>
<p>Se puede decir legalmente lo siguiente</p>
<blockquote class="blockquote">
<p>Con un 95% de confianza se puede sostener que este intervalo de confianza capta el verdadero parámetro de población</p>
</blockquote>
<p>El nivel de confianza refiere al grado de certeza que tenemos de que el parámetro estará contenido en el intervalo que hemos estimado. Por ejemplo, al decir “con un 95% de confianza”, significa que en un 95% de las muestras los intervalos obtenidos comprenderán al verdadero parámetro.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/heis.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>En este práctico realizaremos inferencia sobre dos estimaciones: 1) el ingreso promedio del trabajo de las personas ocupadas y 2) la proporción de hombres y mujeres ocupadas, ambos en Chile en el año 2021.</p>
<p><strong>!MANOS A LA OBRA!</strong></p>
<section id="a-ic-para-medias-con-diseño-muestral" class="level3">
<h3 class="anchored" data-anchor-id="a-ic-para-medias-con-diseño-muestral">a) IC para medias con diseño muestral</h3>
<p>Según el <a href="https://www.ine.gob.cl/docs/default-source/encuesta-suplementaria-de-ingresos/publicaciones-y-anuarios/s%C3%ADntesis-de-resultados/2021/s%C3%ADntesis-nacional-esi-2021.pdf?sfvrsn=ae4f9cef_4">informe de resultados de la ESI 2021</a>, el ingreso medio mensual estimado para la población ocupada en Chile fue de $681.039.</p>
<p>Veamos primero el ingreso medio mensual en nuestra muestra o base de datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(esi<span class="sc">$</span>ing_t_p)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vars     n     mean       sd   median  trimmed      mad min      max
X1    1 37124 586360.4 697362.9 405347.7 474473.1 255411.6   0 38206253
      range skew kurtosis      se
X1 38206253   12   402.32 3619.36</code></pre>
</div>
</div>
<p>Como podemos apreciar, en nuestra muestra el valor promedio del ingreso mensual de las personas ocupadas fue igual a $586.360, por lo cual ya sabemos que se encuentra lejos del parámetro. En inferencia, más que el valor promedio de una variable en la muestra, nos interesa saber en qué medida ese promedio da cuenta del promedio de la población.</p>
<p>Veamos cómo realizar un IC que considere también la estimación puntual pero que sea extrapolable a la población.</p>
<p>La fórmula de IC para medias es:</p>
<p><span class="math display">\[[\overline{x} - z_{a/2}*\frac{sd}{\sqrt{n}} , \overline{x} + z_{a/2}*\frac{sd}{\sqrt{n}}]\]</span> Pero R hace este cálculo por nosotros, aunque es importante entender la lógica que hay detrás. Ahora, estimemos el IC para el ingreso medio de la población ocupada:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>esi_pond <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media =</span> <span class="fu">survey_mean</span>(ing_t_p, <span class="at">vartype =</span> <span class="st">"ci"</span>, <span class="at">levels =</span> <span class="fl">0.95</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="co"># usamos funcion survey_mean</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
    media media_low media_upp
    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 681039.   666563.   695516.</code></pre>
</div>
</div>
<p>Con este resultado, podemos sostenter que:</p>
<ul>
<li>el ingreso medio mensual de la población ocupada en Chile al 2021 alcanzó los $681.039 y,</li>
<li>con un 95% de confianza, este parámetro estará comprendido entre los 666.563 pesos y 695.516 pesos.</li>
</ul>
</section>
<section id="b-ic-para-proporciones-con-diseño-muestral" class="level3">
<h3 class="anchored" data-anchor-id="b-ic-para-proporciones-con-diseño-muestral">b) IC para proporciones con diseño muestral</h3>
<p>Según el informe mencionado, en el año 2021, la composición de la población ocupada a nivel nacional se distribuyó de la siguiente manera: aproximadamente el 58% corresponde a hombres y el 42% a mujeres.</p>
<p>La fórmula de IC para proporciones es:</p>
<p><span class="math display">\[[\overline{p} - z_{a/2}*\sqrt{\frac{p*(1-\overline{p})}{n}} , \overline{p} + z_{a/2}*\sqrt{\frac{p*(1-\overline{p})}{n}}]\]</span></p>
<p>Veamos primero las frecuencias en nuestra muestra o base de datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">frq</span>(esi<span class="sc">$</span>sexo)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=37124 valid N=37124 mean=1.44 sd=0.50

Value  |     N | Raw % | Valid % | Cum. %
-----------------------------------------
Hombre | 20806 | 56.04 |   56.04 |  56.04
Mujer  | 16318 | 43.96 |   43.96 | 100.00
&lt;NA&gt;   |     0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>A nivel muestral, los datos parecieran no alejarse del parámetro. Sin embargo, de todas maneras esto no nos permite realizar inferencia y mucho menos asignar algún grado de probabilidad de acierto (o error) a nuestras estimaciones.</p>
<p>Ahora, estimemos el IC para la proporción de hombres y mujeres ocupadas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>esi_pond <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sexo) <span class="sc">%&gt;%</span> <span class="co"># agrupamos por sexo</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="st">"ci"</span>, <span class="at">levels =</span> <span class="fl">0.95</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  sexo    prop prop_low prop_upp
  &lt;fct&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 Hombre 0.582    0.575    0.590
2 Mujer  0.418    0.410    0.425</code></pre>
</div>
</div>
<p>Con estos resultados podemos concluir que, con un 95% de confianza, la proporción de hombres ocupados a nivel nacional se encuentra entre el 57% y el 59%, mientras que el de las mujeres entre el 41% y el 43%.</p>
</section>
<section id="c-varios-a-la-vez" class="level3">
<h3 class="anchored" data-anchor-id="c-varios-a-la-vez">c) Varios a la vez</h3>
<p>Podemos combinar en un solo código gran parte de la información que necesitamos. Además, podemos complejizar el análisis comparando los valores poblaciones entre grupos. Veamos algunos ejemplos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>esi_pond <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sexo) <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">fr =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="st">"ci"</span>, <span class="at">levels =</span> <span class="fl">0.95</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">fa =</span> <span class="fu">survey_total</span>(<span class="at">vartype =</span> <span class="st">"ci"</span>, <span class="at">levels =</span> <span class="fl">0.95</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">unweighted</span>(<span class="fu">n</span>()))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 8
  sexo      fr fr_low fr_upp       fa   fa_low   fa_upp     n
  &lt;fct&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 Hombre 0.582  0.575  0.590 4801422. 4727453. 4875391. 20806
2 Mujer  0.418  0.410  0.425 3442157. 3381288. 3503026. 16318</code></pre>
</div>
</div>
<p>Aquí tenemos tanto la cantidad <em>(fa)</em> como la proporción <em>(fr)</em> de ocupados según sexo. ¿Y si quisiera saber, por ejemplo, el valor promedio del ingreso mensual entre hombres y mujeres?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>esi_pond <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sexo) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media =</span> <span class="fu">survey_mean</span>(ing_t_p, <span class="at">vartype =</span> <span class="st">"ci"</span>, <span class="at">levels =</span> <span class="fl">0.95</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  sexo     media media_low media_upp
  &lt;fct&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 Hombre 749046.   726663.   771428.
2 Mujer  586178.   569330.   603026.</code></pre>
</div>
</div>
<p>Ahora conocemos el valor puntual y sus IC del ingreso mensual de la población ocupada, según sexo.</p>
</section>
</section>
<section id="contraste-de-hipótesis" class="level1">
<h1>Contraste de hipótesis</h1>
<p>En estadística descriptiva univarada, el contraste de hipótesis se refire a <strong>poner a prueba el valor propuesto/hipotetizado de un parámetro.</strong></p>
<p>Sabemos que:</p>
<p><span class="math inline">\(H_{0} : \mu\)</span> = valor parámetro (la hipótesis que usualmente queremos rechazar)</p>
<p><span class="math inline">\(H_{a} : \mu\)</span> ≠ valor parámetro → <span class="math inline">\(\mu\)</span> &gt; valor parámetro o <span class="math inline">\(\mu\)</span> &lt; valor parámetro (la hipotesis que se deriva de nuestra investigación y es complementaria o diferente a la nula)</p>
<div class="alert alert-info">
<p>Los IC son, a su vez, una prueba de hipótesis implícita. Esto nos lleva a interpretar la confianza y el error como dos caras de una moneda. La confianza nos indica con cuanto grado de certeza podemos afirmar que el IC contendrá el parámetro, o bien, la probabilidad de error que esperamos que exista.</p>
</div>
<p>Si esto lo llevamos a nuestro ejemplo, podemos plantear que el ingreso medio de la población ocupada será mayor a 600.000. Formalmente sería:</p>
<p><span class="math inline">\(H_{0} : \mu\)</span> = 600.000</p>
<p><span class="math inline">\(H_{a} : \mu\)</span> ≠ 600.000 → <span class="math inline">\(\mu\)</span> &gt; 600.000</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>esi_pond <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media =</span> <span class="fu">survey_mean</span>(ing_t_p, <span class="at">vartype =</span> <span class="st">"ci"</span>, <span class="at">levels =</span> <span class="fl">0.95</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="co"># usamos funcion survey_mean</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
    media media_low media_upp
    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 681039.   666563.   695516.</code></pre>
</div>
</div>
<p>Con este resultado podemos afirmar que la media de la variable es 681,039 con un IC del 95% que oscila entre 666,563 y 695,516, por lo que la <span class="math inline">\(H_{0}\)</span> debe ser rechazada (o bien, la <span class="math inline">\(H_{a}\)</span> recibe apoyo).</p>
<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen">Resumen</h2>
<p>Hoy aprendimos a realizar inferencia estádistica en R. En detalle, vimos:</p>
<ol type="1">
<li><p>Establecer el diseño muestral de una base de datos en R.</p></li>
<li><p>Realizar estimaciones puntuales e intervalares para medias y proporciones.</p></li>
<li><p>Contrastar hipótesis univariadas.</p></li>
</ol>
</section>
<section id="video-de-la-sesión" class="level2">
<h2 class="anchored" data-anchor-id="video-de-la-sesión">Video de la sesión</h2>
<div class="quarto-video ratio ratio-16x9"><iframe src="https://www.youtube.com/embed/2KY10sfhXcQ" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Content <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> 2023 by <a href="?var:instructor.url">Andreas Laffert</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-by" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-nc" aria-hidden="true"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></div>   
    <div class="nav-footer-right">Made with <i class="fa-brands fa-r-project" aria-hidden="true"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/Andreas-Lafferte/descriptiva">View the source at <i class="fa-brands fa-github" aria-hidden="true"></i> GitHub</a></div>
  </div>
</footer>



</body></html>