---
title: "Laboratorio de Análisis de Datos"
---

En esta sección se encuentran las **guías prácticas** a desarrollar durante las sesiones del Laboratorio de Análisis de Datos.

Todo el material es accesible desde el menú de la izquierda <--

## Instrucciones generales para las prácticas

- Las instancia prácticas consisten en el desarrollo de una guía práctica cada 2 semanas donde se aplican y profundizan los contenidos de las clases mediante las herramientas del lenguaje R. La organización de estas prácticas se puede revisar en la [planificación del curso](/schedule).

- Estas sesiones acompañarán el desarrollo de las guías prácticas disponibles en este sitio.

- En las prácticas vamos a trabajar con el software R, Versión 4.2.2 

- Para poder tener una asesoría y monitoreo más cercano en el desarrollo de las guías, los estudiantes han sido divididos en grupos asignados a un/a ayudante (ver en UCursos).

- El trabajo con estas guías se organiza en los siguientes momentos:

    + las sesiones de laboratorios serán en modalidad online, en donde el equipo docente guiará el desarrollo del práctico
    + el equipo docente mostrará el código para cada sesión, el cual contendrá los mismos contenidos de las guías alojadas en este sitio
    + en paralelo, cada estudiante realiza esta guía de manera autónoma durante la sesión de laboratorio en su propio computador, apoyándose en el código que mostrarán los apoyos docentes
    + en caso de dudas, las realizan en los foros disponibles o se contactan directamente con su ayudante

## Trabajo con software R

Para los análisis estadísticos de este curso usamos el programa R, en parte porque es gratuito, pero la principal razón es que es de código abierto. Esto quiere decir que cualquier persona puede revisar cómo está hecho y aportar con modificaciones y procedimientos nuevos, como son las librerías que realizan funciones específicas.

El carácter de apertura de R posee muchas ventajas, pero también conlleva complicaciones. Se actualiza permanentemente, así como también las librerías, y esto puede generar problemas de compatibilidad y de fallas en ejecución del código de análisis.

Para minimizar estos posibles problemas en este curso, vamos a:

- trabajar con la misma y última versión de R, que es la 4.2
- evitar uso de tilde, ñ, espacios y mayúsculas tanto en carpetas y archivos, así como también en los nombres de las variables
- al momento de hacer consultas sobre problemas en la ejecución del código, adjuntar la siguiente información:

  1. Código completo hasta que se produce el problema
  2. Indicar línea del código donde se produce el problema
  3. Adjuntar el resultado del output de la información de la sesión (`sessionInfo()`)

### Instalación de R & RStudio {#installR}

Para esta versión del curso vamos a trabajar con el programa R Version 4.2 (se sugiere la última versión 4.2.2) y con RStudio, que ofrece un entorno más amigable para trabajar con R.

Para **instalar R**: ir a [https://cran.r-project.org/index.html](https://cran.r-project.org/index.html) y bajar/instalar la versión correspondiente a la plataforma utilizada (Windows, Mac o Linux)

Para instalar **RStudio**: ir a [https://posit.co/downloads/](https://posit.co/downloads/) y bajar/instalar RStudio desktop, Open Source License (libre).


Si por alguna razón se prefiere trabajar sin descargar, también se puede utilizar RCloud, abajo un tutorial de una versión anterior del curso de estadística multivarada

<div style="width: 100%; height: 600px; overflow: hidden;">
<video  style="width: 100%;" controls>
<source src="https://www.dropbox.com/s/6nqm99dqnjvtmry/rcloud.mp4?raw=1" type="video/mp4">
</video>
</div>


### Sobre el trabajo en hojas de código en RStudio {#codigoR}

- El trabajo de análisis en RStudio se efectua en una _hoja de código_ (o R script o sintaxis, o para los usuarios de Stata la _do-file_), que es donde se anotan los comandos y funciones. Para abrir una hoja, en RStudio ir a File > New File > R Script (o ctrl+shift+N),y aparecerá un panel con una pestaña "Untitled" (sin título). Esta es la hoja de código donde se anotan los comandos.

- Los contenidos de las hojas de código son básicamente 2:

  - comandos o funciones: se escriben en la hoja, y para ejecutarlos se debe posicionar el cursor en la línea respectiva y ctrl+enter, el resultado aparecerá en el panel de resultados o _Consola_.
  - texto: para escribir títulos, comentarios, y todo lo que permita entender qué se está haciendo, al principio de la línea respectiva escribir el signo `#`

- Para grabar nuestra hoja de código y así respaldar nuestros análisis, File > Save (o ctrl+s), y dar un nombre al archivo. Recordar: breve, sin espacios ni tildes ni eñes. Por defecto, la extensión de estos archivos es .R


